### ISSUE TITLE
'IUnknown': ambiguous symbol

### ISSUE THREAD

**Issue by raymrdc** [Const-me/ComLightInterop#1]
ComLight::IUnknown is conflicting with IUnknown in file ocidl.h

Excerpt of the compiler output. The other lines are almost similar error messages

2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.h(463,14): error C2872: 'IUnknown': ambiguous symbol
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwnbase.h(109,9): message : could be 'IUnknown'
2>C:\Users\Name\source\repos\TempProj\ComLightLib\unknwn.h(26,27): message : or 'ComLight::IUnknown'

a Temporary project (.Net5) was added to github:
raymrdc/TempProj

**Comment by Const-me** [comment]
@raymrdc Please post complete compiler output, and ideally a source code that reproduces the problem.

**Comment by raymrdc** [comment]
Excerpt of the compiler output. The other lines are almost similar error messages

2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.h(463,14): error C2872: 'IUnknown': ambiguous symbol
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwnbase.h(109,9): message : could be 'IUnknown'
2>C:\Users\Name\source\repos\TempProj\ComLightLib\unknwn.h(26,27): message : or       'ComLight::IUnknown'

a Temporary project (.Net5) was added to github: 
raymrdc/TempProj

**Comment by Const-me** [comment]
@raymrdc Not sure that’s something I’m willing to fix, but I’ve documented the behavior, in the “[Known Issues](https://github.com/Const-me/ComLightInterop#known-issues)” section of the readme.

**Comment by raymrdc** [comment]
changes made documented in the known issues fix the issues.
